FROM amazoncorretto:17-alpine-jdk
MAINTAINER jlengrand
COPY build/libs/checkout-example-advanced-0.0.1-SNAPSHOT.jar checkout-example-advanced-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/checkout-example-advanced-0.0.1-SNAPSHOT.jar"]
