FROM amazoncorretto:17-alpine-jdk
MAINTAINER jlengrand
COPY build/libs/adyen-java-spring-online-payments-checkout-advanced-0.0.1-SNAPSHOT.jar adyen-java-spring-online-payments-checkout-advanced-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/adyen-java-spring-online-payments-checkout-advanced-0.0.1-SNAPSHOT.jar"]
