FROM amazoncorretto:17-alpine-jdk
COPY build/libs/adyen-java-spring-online-payments-checkout-advanced.jar adyen-java-spring-online-payments-checkout-advanced.jar
ENTRYPOINT ["java","-jar","/adyen-java-spring-online-payments-checkout-advanced.jar"]
