version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/checkout-example"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/checkout-example-advanced"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/paybylink-example"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/giftcard-example"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/subscription-example"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/giving-example"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/in-person-payments-example"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/authorisation-adjustment-example"
    schedule:
      interval: "daily"