version: 2
updates:

  - package-ecosystem: "gradle" 
    directory: "/checkout-example" 
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle" 
    directory: "/subscription-example" 
    schedule:
      interval: "daily"
