tasks:
- before: sdk install java 17.0.4.1-tem < /dev/null
- init: ./gradlew bootJar
  command: |
        if [ [[ -z ${ADYEN_API_KEY+x} ]] || [[ -z ${ADYEN_CLIENT_KEY+x} ]] || [[ -z ${ADYEN_MERCHANT_ACCOUNT+x} ]]; then
            echo "Expected environment variables not found. Please set the ADYEN_API_KEY, ADYEN_CLIENT_KEY, ADYEN_MERCHANT_ACCOUNT environment variables and rerun session https://gitpod.io/variables."
        else
            ./gradlew bootRun
        fi

# exposed ports
ports:
- port: 8080
  onOpen: open-preview
  visibility: public

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot
