tasks:
- init: ./gradlew bootJar
  command: if [ -n "$ADYEN_API_KEY" ]; then ./gradlew bootRun else echo "$ADYEN_API_KEY not found. Please set environment variables and rerun session https://gitpod.io/variables." fi

# exposed ports
ports:
- port: 8080
  onOpen: open-preview

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot
