FROM amazoncorretto:17-alpine-jdk
MAINTAINER jlengrand
COPY build/libs/giving-example-0.0.1-SNAPSHOT.jar giving-example-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/giving-example-0.0.1-SNAPSHOT.jar"]
