FROM amazoncorretto:17-alpine-jdk
COPY build/libs/adyen-java-spring-online-payments-authorisation-adjustment-0.0.1-SNAPSHOT.jar adyen-java-spring-online-payments-authorisation-adjustment-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/adyen-java-spring-online-payments-authorisation-adjustment-0.0.1-SNAPSHOT.jar"]
