FROM --platform=linux/amd64 amazoncorretto:17-alpine-jdk
MAINTAINER jlengrand
COPY build/libs/paybylink-example-0.0.1-SNAPSHOT.jar paybylink-example-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/paybylink-example-0.0.1-SNAPSHOT.jar"]
