name: Build In-Person Payments

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'in-person-payments-example/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'in-person-payments-example/**'

jobs:

  build-in-person-payments:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    name: in-person-payments-example build with Java ${{ matrix.Java }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Grant execute permission for gradlew
        run: chmod +x in-person-payments-example/gradlew
      - name: Build with Gradle
        run: cd in-person-payments-example; ./gradlew build

