name: Build Giftcard

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'giftcard-example/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'giftcard-example/**'

jobs:

  build-giftcard:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    name: giftcard-example build with Java ${{ matrix.Java }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Grant giftcard-example execute permission for gradlew
        run: chmod +x giftcard-example/gradlew
      - name: Build giftcard-example with Gradle
        run: cd giftcard-example; ./gradlew build
