name: Build Checkout

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'checkout-example/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'checkout-example/**'

jobs:
  build-checkout:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    name: checkout-example build with Java ${{ matrix.Java }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Grant checkout-example execute permission for gradlew
        run: chmod +x checkout-example/gradlew
      - name: Build checkout-example with Gradle
        run: cd checkout-example; ./gradlew build
