name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-checkout:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '21' ]
    name: Java ${{ matrix.Java }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Grant checkout-example execute permission for gradlew
        run: chmod +x gradlew
      - name: Build all examples with Gradle
        run: ./gradlew build
