name: Build Subscription

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'subscription-example/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'subscription-example/**'

jobs:

  build-subscription:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    name: subscription-example build with Java ${{ matrix.Java }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Grant execute permission for gradlew
        run: chmod +x subscription-example/gradlew
      - name: Build with Gradle
        run: cd subscription-example; ./gradlew build
