name: Build PayByLink

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'paybylink-example/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'paybylink-example/**'

jobs:

  build-paybylinks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    name: paybylink-example build with Java ${{ matrix.Java }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Grant execute permission for gradlew
        run: chmod +x paybylink-example/gradlew
      - name: Build with Gradle
        run: cd paybylink-example; ./gradlew build

