name: E2E Giving

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'giving-example/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'giving-example/**'

jobs:

  giving:
    runs-on: ubuntu-latest
    steps:
      - name: Giving project
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x giving-example/gradlew
      - name: Build giving-example with Gradle
        run: cd giving-example; ./gradlew build
      - name: Build giving-example image
        run: docker build -t giving-example:latest giving-example
      - name: Start giving-example container
        run: docker run --rm -d --name giving-example -p 8080:8080 -e ADYEN_API_KEY="${{ secrets.ADYEN_API_KEY }}" -e ADYEN_MERCHANT_ACCOUNT=${{ secrets.ADYEN_MERCHANT_ACCOUNT }} -e ADYEN_CLIENT_KEY=${{ secrets.ADYEN_CLIENT_KEY }} -e ADYEN_HMAC_KEY=${{ secrets.ADYEN_HMAC_KEY }} giving-example:latest
      - name: Run testing suite
        run: docker run --rm --name adyen-testing-suite -e PLAYWRIGHT_FOLDERNAME=giving -e ADYEN_HMAC_KEY=${{ secrets.ADYEN_HMAC_KEY }} --network host ghcr.io/adyen-examples/adyen-testing-suite:main


