name: E2E Checkout

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'checkout-example/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'checkout-example/**'

jobs:
  # e2e testing with Adyen.Web Drop-in/Components v5 (see /_archive/v5 folder)
  checkout-v5:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x checkout-example/_archive/v5/gradlew
      - name: Build checkout-example/v5 with Gradle
        run: cd checkout-example/_archive/v5; ./gradlew build
      - name: Build checkout-example image
        run: docker build -t checkout-example-v5:latest -f ./checkout-example/_archive/v5/Dockerfile ./checkout-example/_archive/v5
      - name: Start checkout-example container
        run: docker run --rm -d --name checkout-example-v5 -p 8080:8080 -e ADYEN_API_KEY="${{ secrets.ADYEN_API_KEY }}" -e ADYEN_MERCHANT_ACCOUNT=${{ secrets.ADYEN_MERCHANT_ACCOUNT }} -e ADYEN_CLIENT_KEY=${{ secrets.ADYEN_CLIENT_KEY }} -e ADYEN_HMAC_KEY=${{ secrets.ADYEN_HMAC_KEY }} checkout-example-v5:latest
      - name: Run testing suite
        run: docker run --rm --name adyen-testing-suite -e PLAYWRIGHT_FOLDERNAME=checkout/v5 -e ADYEN_HMAC_KEY=${{ secrets.ADYEN_HMAC_KEY }} --network host ghcr.io/adyen-examples/adyen-testing-suite:main

  # e2e testing with Adyen.Web Drop-in/Components v6
  checkout-v6:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x checkout-example/gradlew
      - name: Build checkout-example with Gradle
        run: cd checkout-example; ./gradlew build
      - name: Build checkout-example image
        run: docker build -t checkout-example:latest checkout-example
      - name: Start checkout-example container
        run: docker run --rm -d --name checkout-example -p 8080:8080 -e ADYEN_API_KEY="${{ secrets.ADYEN_API_KEY }}" -e ADYEN_MERCHANT_ACCOUNT=${{ secrets.ADYEN_MERCHANT_ACCOUNT }} -e ADYEN_CLIENT_KEY=${{ secrets.ADYEN_CLIENT_KEY }} -e ADYEN_HMAC_KEY=${{ secrets.ADYEN_HMAC_KEY }} checkout-example:latest
      - name: Run testing suite
        run: docker run --rm --name adyen-testing-suite -e PLAYWRIGHT_FOLDERNAME=advanced-checkout/v6 -e ADYEN_HMAC_KEY=${{ secrets.ADYEN_HMAC_KEY }} --network host ghcr.io/adyen-examples/adyen-testing-suite:main
