name: E2E In-Person Payments

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'in-person-payments-example/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'in-person-payments-example/**'

jobs:

  in-person-payments:
    runs-on: ubuntu-latest
    steps:
      - name: In-person Payments project
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x in-person-payments-example/gradlew
      - name: Build in-person-payments-example with Gradle
        run: cd in-person-payments-example; ./gradlew build
      - name: Build in-person-payments-example image
        run: docker build -t in-person-payments-example-image:latest in-person-payments-example
      - name: Start in-person-payments-example container, set ADYEN_TERMINAL_API_CLOUD_ENDPOINT to default docker bridge and port 3000
        run: docker run --rm -d --name in-person-payments-example-image -p 8080:8080 -e ADYEN_API_KEY="${{ secrets.ADYEN_API_KEY }}" -e ADYEN_HMAC_KEY=${{ secrets.ADYEN_HMAC_KEY }} -e ADYEN_TERMINAL_API_CLOUD_ENDPOINT=http://172.17.0.1:3000 -e ADYEN_POS_POI_ID=V400m-123456789 in-person-payments-example-image:latest
      - name: Start the Adyen Mock Terminal API Application on port 3000
        run: docker run --rm -d --name adyen-mock-terminal-api -p 3000:3000 -e PORT=3000 ghcr.io/adyen-examples/adyen-mock-terminal-api:main
      - name: Run testing suite against in-person-payments-example-image
        run: docker run --rm --name adyen-testing-suite -e ADYEN_HMAC_KEY=${{ secrets.ADYEN_HMAC_KEY }} -e PLAYWRIGHT_FOLDERNAME=in-person-payments --network host ghcr.io/adyen-examples/adyen-testing-suite:main
