name: E2E Authorisation Adjustment

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'authorisation-adjustment-example/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'authorisation-adjustment-example/**'

jobs:

  authorisation-adjustment:
    runs-on: ubuntu-latest
    steps:
      - name: Authorisation Adjustment project
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x authorisation-adjustment-example/gradlew
      - name: Build authorisation-adjustment-example with Gradle
        run: cd authorisation-adjustment-example; ./gradlew build
      - name: Build authorisation-adjustment-example image
        run: docker build -t authorisation-adjustment-example:latest authorisation-adjustment-example
      - name: Start authorisation-adjustment container
        run: docker run --rm -d --name authorisation-adjustment-example -p 8080:8080 -e ADYEN_API_KEY="${{ secrets.ADYEN_API_KEY }}" -e ADYEN_MERCHANT_ACCOUNT=${{ secrets.ADYEN_MERCHANT_ACCOUNT }} -e ADYEN_CLIENT_KEY=${{ secrets.ADYEN_CLIENT_KEY }} -e ADYEN_HMAC_KEY=${{ secrets.ADYEN_HMAC_KEY }} authorisation-adjustment-example:latest
      - name: Run testing suite
        run: docker run --rm --name adyen-testing-suite -e PLAYWRIGHT_FOLDERNAME=authorisation-adjustment -e ADYEN_HMAC_KEY=${{ secrets.ADYEN_HMAC_KEY }} --network host ghcr.io/adyen-examples/adyen-testing-suite:main


