FROM amazoncorretto:17-alpine-jdk
COPY build/libs/adyen-java-spring-in-person-payments-0.0.1-SNAPSHOT.jar adyen-java-spring-in-person-payments-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/adyen-java-spring-in-person-payments-0.0.1-SNAPSHOT.jar"]